[project]
name = "icicle-playgrounds"
version = "0.1.0"
description = "SDK to interact with the ICICLE Model & Data Playgrounds"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "litserve>=0.2.10",
    "pydantic-settings>=2.9.1",
]
